In [2]:
import pandas as pd
import numpy as np

In [8]:
emotion_df = pd.read_csv("./Dataset/World_Happiness_Report_2024.csv")
emotion_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.164055,0.881686,0.414297,0.258195
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.187297,0.850035,0.481421,0.237092
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.117861,0.706766,0.516907,0.275324
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.160098,0.731109,0.479835,0.267175
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.234157,0.775620,0.613513,0.267919

In [9]:
emotion_df.drop_duplicates()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.164055,0.881686,0.414297,0.258195
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.187297,0.850035,0.481421,0.237092
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.117861,0.706766,0.516907,0.275324
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.160098,0.731109,0.479835,0.267175
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.234157,0.775620,0.613513,0.267919
...,...,...,...,...,...,...,...,...,...,...,...
2358,Zimbabwe,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.050874,0.830652,0.658434,0.235354
2359,Zimbabwe,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.002848,0.788523,0.660658,0.345736
2360,Zimbabwe,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.079007,0.756945,0.609917,0.241682
2361,Zimbabwe,2022,3.296220,7.670073,0.666172,54.525002,0.651987,-0.072935,0.752632,0.640609,0.191350
2362,Zimbabwe,2023,3.572386,7.678590,0.693817,55.000000,0.734613,-0.068837,0.757494,0.609752,0.178953

In [24]:
# the most recent data
emotion_2023 = emotion_df[emotion_df["year"] == 2023]
emotion_2023

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
14,Afghanistan,2023,1.445909,NaN,0.368478,55.200001,0.228301,NaN,0.738471,0.260513,0.460167
30,Albania,2023,5.444691,9.688706,0.690753,69.199997,0.871545,0.067885,0.855425,0.597349,0.314227
63,Argentina,2023,6.393229,9.993596,0.892118,67.300003,0.831684,-0.129061,0.846094,0.720122,0.301162
80,Armenia,2023,5.679090,9.729613,0.819338,68.199997,0.819376,-0.179444,0.680709,0.574717,0.422631
97,Australia,2023,7.024582,10.846434,0.896460,71.199997,0.875769,0.187309,0.481580,0.731053,0.248163
...,...,...,...,...,...,...,...,...,...,...,...
2295,Venezuela,2023,5.765363,NaN,0.884668,63.700001,0.756530,NaN,0.825393,0.757685,0.300038
2313,Vietnam,2023,6.325115,9.392351,0.844905,65.699997,0.955560,-0.159114,0.655275,0.710068,0.119510
2327,Yemen,2023,3.531574,NaN,0.824958,56.599998,0.582724,NaN,0.771464,0.446534,0.340794
2344,Zambia,2023,3.685568,8.115053,0.664099,56.099998,0.854004,0.092377,0.814191,0.652999,0.359132
2362,Zimbabwe,2023,3.572386,7.678590,0.693817,55.000000,0.734613,-0.068837,0.757494,0.609752,0.178953

In [31]:
# filter out nan Generosity and strip strings
emotion_2023 = emotion_2023[emotion_2023['Generosity'].notnull()]
emotion_2023["Country name"] = emotion_2023["Country name"].str.strip()
emotion_2023

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
30,Albania,2023,5.444691,9.688706,0.690753,69.199997,0.871545,0.067885,0.855425,0.597349,0.314227
63,Argentina,2023,6.393229,9.993596,0.892118,67.300003,0.831684,-0.129061,0.846094,0.720122,0.301162
80,Armenia,2023,5.679090,9.729613,0.819338,68.199997,0.819376,-0.179444,0.680709,0.574717,0.422631
97,Australia,2023,7.024582,10.846434,0.896460,71.199997,0.875769,0.187309,0.481580,0.731053,0.248163
113,Austria,2023,6.635664,10.930412,0.874427,71.400002,0.874083,0.209268,0.529430,0.712497,0.239608
...,...,...,...,...,...,...,...,...,...,...,...
2260,Uruguay,2023,6.661722,10.122264,0.908374,67.500000,0.904164,-0.050256,0.661658,0.753448,0.264817
2277,Uzbekistan,2023,6.385361,9.025871,0.908859,65.900002,0.926784,0.247137,0.649540,0.751747,0.202207
2313,Vietnam,2023,6.325115,9.392351,0.844905,65.699997,0.955560,-0.159114,0.655275,0.710068,0.119510
2344,Zambia,2023,3.685568,8.115053,0.664099,56.099998,0.854004,0.092377,0.814191,0.652999,0.359132
2362,Zimbabwe,2023,3.572386,7.678590,0.693817,55.000000,0.734613,-0.068837,0.757494,0.609752,0.178953